### ISSUE TITLE
Error con Ip, subdominio y puerto en la URL

### ISSUE THREAD

**Issue by and23War** [pabhoz/FoxFramework#1]
Hola Pablo,

creo que se debería añadir al regex del ROOT, "\." para poder tomar los subdominios y Ip en las URL, también puede ser un ":" para tomar los puertos(cuando se trabaja como "localhost:8080"), quedaría así '/[^a-zA-Z0-9]\.:/i' 

Adjunto imagen con el error.
<img width="1674" alt="captura de pantalla 2018-01-29 a la s 8 54 50 a m" src="https://user-images.githubusercontent.com/32577584/35517172-ac8e924a-04db-11e8-86df-30b8f06ca29a.png">

**Comment by pabhoz** [comment]
Excelente, muchas gracias por el aporte.

**Comment by pabhoz** [comment]
Fixed by @and23War at https://github.com/pabhoz/FoxFramework/commit/f3c8f3deb5430f6ebe04ffb2555b211e5728f1a6
